# Generated by Django 6.0.5 on 2026-07-01 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='participacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='participacion',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
