# Generated by Django 6.0.5 on 2026-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_participacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tecnicos/'),
        ),
    ]
